notifications:
  email: false
language: generic
sudo: required
env:
  global:
    - PREBUILT_SHEN_VERSION=3.0.0
matrix:
  include:
  - os: linux
    env:
      - OS_NAME=linux
      - BUNDLE_EXT=tar.gz
      - MAKE_BUILD_TARGET=all
      - SHEN=./shen-scheme-0.22-linux-bin/bin/shen-scheme
    install:
      - wget http://mr.gy/blog/clozure-cl_1.11_amd64.deb
      - sudo dpkg -i clozure-cl_1.11_amd64.deb
      - wget http://http.us.debian.org/debian/pool/main/s/sbcl/sbcl_1.3.14-2+b1_amd64.deb
      - sudo dpkg -i sbcl_1.3.14-2+b1_amd64.deb
      - wget "https://github.com/tizoc/shen-scheme/releases/download/0.22/shen-scheme-0.22-linux-bin.tar.gz"
      - tar xzf "shen-scheme-0.22-linux-bin.tar.gz"
  - os: osx
    env:
      - OS_NAME=macos
      - BUNDLE_EXT=tar.gz
      - HOMEBREW_NO_AUTO_UPDATE=1
      - MAKE_BUILD_TARGET=sbcl
      - SHEN=./shen-scheme-0.22-osx-bin/bin/shen-scheme
    before_install:
      - test -f /usr/local/opt/sbcl/installed || { rmdir /usr/local/opt/sbcl; brew update; brew install sbcl; touch /usr/local/opt/sbcl/installed; }
      - brew link sbcl
    install:
      - wget "https://github.com/tizoc/shen-scheme/releases/download/0.22/shen-scheme-0.22-osx-bin.tar.gz"
      - tar xzf "shen-scheme-0.22-osx-bin.tar.gz"
    before_cache:
      - brew cleanup
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Cellar/sbcl
        - /usr/local/opt/sbcl
  - os: windows
    language: shell
    env:
      - OS_NAME=windows
      - BUNDLE_EXT=zip
      - MAKE_BUILD_TARGET=sbcl
      - SBCL_PATH="C:/Program Files/Steel Bank Common Lisp/1.4.14"
      - SHEN=./shen-scheme-0.22-windows-bin/bin/shen-scheme.exe
    install:
      - choco install make
      - curl -L "https://netcologne.dl.sourceforge.net/project/sbcl/sbcl/1.4.14/sbcl-1.4.14-x86-64-windows-binary.msi" -o sbcl.msi
      - powershell -Command "Start-Process msiexec.exe -Wait -ArgumentList '/i sbcl.msi /qn'"
      - curl -L "https://github.com/tizoc/shen-scheme/releases/download/0.22/shen-scheme-0.22-windows-bin.zip" -o "shen-scheme-0.22-windows-bin.zip"
      - 7z x "shen-scheme-0.22-windows-bin.zip"
addons:
  apt:
    packages:
      - clisp
      - ecl
      - libffi-dev
script:
  - make fetch
  - make precompile
  - make $MAKE_BUILD_TARGET
before_deploy:
  - make release
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "windows" ]]; then
      make source-release;
    fi;
deploy:
  provider: releases
  api_key:
    secure: "Sn723VHbd3S+e5Zu70R7K/Vjus0oIJLK3aJDz5gcToJxN7xPEIDo+MynKy1K9Fs4IxTTPrXoptuRxCiliblQwkma9ubw/u5Emb3j3MGM4qyLDQKZEUTUPkHHsOK+PwDGv8xmmsFV9W7/CX55shJFSPINDNW2wk/fg4lzgEKO6EUgURdvKg6m8LlvkSMtqo63VXCgZU/OABUhKnounrCBzE9r5arIchXwkEn0HOOEvfGZR7opMJrdWl3IbPGN6zQJJDay7s8UTjNG/951hSGxvFaBF0FTDchzzI4TQkF587w6Lb/Q9skXwkGGWsK36s+eUIUyrrMCaIDHwBNYPY57eLGRSxcOlIsyUQZTrE7OT/hYzSdBo3EhpXeXbdHQoVzmSQ4nu3nm35tb8jKZ8+VNzWqi+dLWnK1hU+RzU+6zYvxfOFsmxAgiz3LnWY9fyrrdxrlhckJuu2TKxEoNV0WfevpV3vVDLOb3mDNoVS7/DKLEo0OqBrSjTzHJf8xc2Yb1fthEbc2leMyTEZHZNc6vhTPPrUwCths2fzxiT5mMO3jYQOQ3zmhE+CkofRmgWJbGVoUHggUyMSk7rlXI+45CpTaSYqxSFJFAr1owkBNZefFFAE4/9f3JEPtol2PaYRgQ6Tv6qJwyjYjAB7jglpGc5Bv08P4XiFjALjw2rqQSPfI="
  file:
    - release/shen-cl-${TRAVIS_TAG}-${OS_NAME}-prebuilt.${BUNDLE_EXT}
    - release/shen-cl-${TRAVIS_TAG}-sources.${BUNDLE_EXT}
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: Shen-Language/shen-cl
